### ISSUE TITLE
Request for PHC icon similar to Lifeology icon

### ISSUE THREAD

**Issue by jhbeard** [lifeomic/chromicons#95]
I would like to request a Chromicon version of the symbol from the current PHC logo. This would be similar to what you have in Chromicons for Lifeology and helpful for diagrams.

**Comment by ynotdraw** [comment]
Hey @jhbeard , thanks for reporting! We went ahead and got this added in the latest version of Chromicons (`v2.3.0`). Let me know if you have any issues adopting it!
